### PR TITLE
Consolidate the versions

### PR DESCRIPTION
**Pull request by Fokko**
Generally, it is a bad practice to use different versions of Spark together, therefore I'd suggest to set it to 2.2.2 for now using a Maven property.

### CODE REVIEW

**Comment by arvindshmicrosoft** [comment]
@Fokko could you kindly rebase / merge your work on top of master so that we can merge?

**Comment by Fokko** [comment]
Of course @arvindshmicrosoft. Thanks for pinging me!

**Comment by arvindshmicrosoft** [comment]
Sorry one more thing - looks like the merge somehow removed the <provided> property you had added in the previous PR. Could you verify that as well and push up another commit to ensure we keep the <provided> attribute per your previous one?

**Comment by Fokko** [comment]
Whoops, that wasn't my intention. I've restored the provided property.

**Pull request merged**
