### PR TITLE
Set Scala versions using properties

### PR DESCRIPTION
**Pull request by Fokko**
Make sure that we set the Scala version at a single place, and that makes it easier to override the properties to set the Scala version of our liking.

### CODE REVIEW

**Comment by arvindshmicrosoft** [comment]
@Fokko would you please rebase / merge your work against current master so that we can do a clean merge post approval?

**Comment by Fokko** [comment]
Thanks, @arvindshmicrosoft for the review, I've swapped the properties.

**Comment by arvindshmicrosoft** [comment]
Thanks @Fokko - apologies but it looks like your latest commit did not really change to the desired behavior. Can you double-check?

**Comment by arvindshmicrosoft** [comment]
Hello again @Fokko - could you please double-check your latest commit? It seems to not have the correct property names as we discussed. As previously mentioned we would like to have `scala.version` as `2.11` and `scala.binary.version` to include the minor version i.e. `2.11.8`

**Comment by Fokko** [comment]
@arvindshmicrosoft I misinterpreted your comment, and I disagree with the suggestion. I would keep it congruent with Spark: https://github.com/apache/spark/blob/master/pom.xml#L164

**Pull request merged**
