### PR TITLE
Improvements in Spark MSSQL Connector

### PR DESCRIPTION
**Pull request by chetkhatri**
What were proposed in this Pull Request ?
* Wrong function name call in README.md
* Default batch size in Bulk load should not be '0', otherwise it will be same as row by row insert.
How this Pull Request is tested ?
* Building and packaging locally and running on Spark Cluster.

Thank you for great spark package :)

### CODE REVIEW

**Comment by chetkhatri** [comment]
@zeqicui @allenwux Please review PR and do needful.

**Comment by zeqicui** [comment]
I am not the maintainer of this repository anymore and do not have admin rights to approve your PR. Please ping @allenwux moving forward.

However to answer your question, a batch size of 0 indicates writing the entire partition as one batch. This is mentioned in the [JDBC driver documentation](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-2017).

**Comment by chetkhatri** [comment]
@zeqicui But I see here that https://blogs.msdn.microsoft.com/sqlcat/2018/05/12/turbo-boost-data-loads-from-spark-using-sql-spark-connector/ batch size should be more than 0 always be.

**Comment by allenwux** [comment]
@chetkhatri Zeqi is right about the default batch size. Practically you should always set the batch size, so the blog is also correct. We are happy the take the doc changes if you can revert the batchsize change. Thanks!

**Comment by arvindshmicrosoft** [comment]
Thank you @chetkhatri for the contribution. Unfortunately, this project is not actively maintained. It looks the changes in your PR are subsumed in other changes which happened since, and hence I am closing this PR.

**Pull request closed without merging**
